In [2]:
import numpy as np

a = np.array([34,53,55])
b = np.array([45,66,33])

a+b

array([ 79, 119,  88])

In [3]:
a-b

array([-11, -13,  22])

In [4]:
a/b

array([0.75555556, 0.8030303 , 1.66666667])

In [5]:
scalar=2

In [6]:
list_a=[10,11,12,13,14,15]
print(list_a)

[10, 11, 12, 13, 14, 15]


In [10]:
list_as_array= np.array(list_a)
print(list_as_array)

[10 11 12 13 14 15]
