In [2]:
import numpy as np

a = np.array([34,53,55])
b = np.array([45,66,33])

a+b

array([ 79, 119,  88])

In [3]:
a-b

array([-11, -13,  22])

In [4]:
a/b

array([0.75555556, 0.8030303 , 1.66666667])

In [5]:
scalar=2

In [6]:
list_a=[10,11,12,13,14,15]
print(list_a)

[10, 11, 12, 13, 14, 15]


In [10]:
list_as_array= np.array(list_a)
print(list_as_array)

[10 11 12 13 14 15]


In [11]:
scalar=2

In [12]:
list_as_array=np.array(list_a)
print(list_as_array)

[10 11 12 13 14 15]


In [13]:
scalar*list_a #output is not an operation of scalar vector multiplication

[10, 11, 12, 13, 14, 15, 10, 11, 12, 13, 14, 15]

In [14]:
scalar*list_as_array #this is scalar vector multiplication

array([20, 22, 24, 26, 28, 30])

In [16]:
#dot product
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
print(np.dot(a,b))

130


In [20]:
c= np.array([11,12,13,14,15])

In [18]:
np.dot(b,a) #property of dot product

130

In [21]:
first_result=np.dot(a,b+c)
print(first_result)    #property of dot product

335


In [22]:
second_result=np.dot(a,b)+np.dot(a,c)
print(second_result)

335


In [23]:
#Scalar and Vector projection

import numpy as np 
from numpy import linalg as lng

In [24]:
a= np.array([10,20,30,40,50])
b= np.array([60,70,80,90,100])

In [25]:
lng.norm(a)

74.16198487095663

In [0]:
vector_projection=(np.dot(a,b)/np.dot(b,b))*(b)
print(vector_projection)