In [3]:
#Gaussian elimination and finding the inverse matrix

import numpy as np 

In [4]:
A= np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [5]:
Ainv=np.linalg.inv(A)
Ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [6]:
b=np.array([5,11])
b

array([ 5, 11])

In [7]:
x=np.dot(Ainv,b)
x

array([1., 2.])

In [8]:
np.dot(A,x)

array([ 5., 11.])

In [11]:
#Inverse and determinant
A=np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [12]:
det=np.linalg.det(A)
det

-2.0000000000000004

In [13]:
B=np.array([[3,1],[6,2]])
B

array([[3, 1],
       [6, 2]])

In [14]:
np.linalg.det(A)
det

-2.0000000000000004

In [16]:
B=np.array([[3,1],[6,2]])
B

array([[3, 1],
       [6, 2]])

In [5]:
#Some Examples in TensorFlow
import tensorflow as tf


In [6]:
x_tf = tf.Variable(25, dtype=tf.int16) # dtype is optional
x_tf

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=25>

In [7]:
X_tf = tf.Variable([[25, 2], [5, 26], [3, 7]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]], dtype=int32)>

In [9]:
tf.rank(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [10]:
tf.shape(X_tf)


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

In [11]:
X_tf[1,:]


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 5, 26], dtype=int32)>

In [12]:
X_tf[:,1]


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 2, 26,  7], dtype=int32)>

In [4]:
X


NameError: name 'X' is not defined